# Generated by Django 4.2.13 on 2024-05-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
